### PR TITLE
Storage blocks tags

### PR DESCRIPTION
**Pull request by JaisDK**

### CODE REVIEW

**Comment by JaisDK** [comment]
Is there a reason why you have not included a Tungsten block? It would be useful as not many other mods provide that resources.

**Comment by kwpugh** [comment]
Why?  What would be the use of storage block tags?

And the mod does not have Tungsten, it is Tungsten-Carbide, so it would be a Tungsten-Carbide Block.

**Comment by JaisDK** [comment]
For consistency and inter-mod compatibility, like all other mods and Forge does it. Why do you have ore tags?

There's Tungsten Ore, Tungsten Dust and Tungsten Ingots but the mod does not have Tungsten?

**Comment by kwpugh** [comment]
Sorry, my bad, I was confused.  I forgot there was a tungsten ingot.

There are item tags for the ores, for use in recipes.

What mod are you trying to use this with that you want storage block tags?

**Comment by JaisDK** [comment]
Productive Bees, it adds resource bees which uses the blocks as flowers. It's a lot easier to support materials from other mods when the blocks are tagged.

**Comment by JaisDK** [comment]
fyi it's not me poking you on discord

**Comment by kwpugh** [comment]
Who's Mickey?

**Comment by kwpugh** [comment]
Add tags and Tungsten block to latest update.

**Pull request closed without merging**
